=== Guillemj98/ActividadesLMSGI/12_Deberes/restricciones.XSD
<?xml version="1.0" ?>
<xs:schema  xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Ciudad">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Nombre">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="[A-Z][a-zA-Z]{2,19}"></xs:pattern>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="Poblacion">
                    <xs:simpleType>
                        <xs:restriction base="xs:integer">
                            <xs:minExclusive value="99"></xs:minExclusive>
                            <xs:maxExclusive value="100001"></xs:maxExclusive>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="alcalde">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[A-Z][a-z]{2,19}"></xs:pattern>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="apellido">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[A-Z][a-zA-Z]+(\s*[A-Z][a-zA-Z]+){0,1}"></xs:pattern>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="telefono">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="\+34\d{9}"></xs:pattern>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="Tarjeta_credito" type="xs:integer"></xs:element>
                            <xs:element name="Correo_electronico">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}"></xs:pattern>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="edad">
                            <xs:simpleType>
                                <xs:restriction base="xs:integer">
                                    <xs:minExclusive value="17"></xs:minExclusive>
                                    <xs:maxExclusive value="121"></xs:maxExclusive>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
                <xs:element name="funcionarios">
                    <xs:complexType>
                        <xs:sequence>
                             <xs:element name="funcionario" minOccurs="1" maxOccurs="unbounded">
                                <xs:complexType>
                                     <xs:sequence>
                                        <xs:element name="Nombre_completo">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:maxLength value="50"></xs:maxLength>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="Codigo_postal">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:pattern value="\d{5}"></xs:pattern>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="fecha_nacimiento" >
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:pattern value="\d{2}/\d{2}/\d{4}"></xs:pattern>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="contrasenia">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:pattern value="[A-Z](\d{2})+[%$@!].*"></xs:pattern>
                                                    <xs:minLength value="10"></xs:minLength>                                                   
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="Cuenta_bancaria">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string ">
                                                    <xs:pattern value="ES\d{4}\s\d{4}\s\d{4}\s\d{4}"></xs:pattern>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>    
                                     </xs:sequence>
                                     <xs:attribute name="Id">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <xs:pattern value="([a-zA-Z\d]{1,10})"></xs:pattern>
                                            </xs:restriction>
                                        </xs:simpleType>
                                     </xs:attribute>
                                </xs:complexType>
                            </xs:element>
                         </xs:sequence>                        
                    </xs:complexType>
                </xs:element>            
            </xs:sequence>
            <xs:attribute name="codigo_identificador_ciudad">
                <xs:simpleType>
                    <xs:restriction base ="xs:string">
                        <xs:pattern value="\D{2}-\d{2,5}"></xs:pattern>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>      
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Guillemj98/ActividadesLMSGI/12_Deberes/restricciones.xml
<?xml version="1.0" encoding="UTF-8"?>
<Ciudad xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation= "restricciones.XSD" codigo_identificador_ciudad="AB-12345">
<Nombre>Madrid</Nombre>
<Poblacion>50000</Poblacion>
<alcalde edad="58">
    <nombre>Pepe</nombre>
    <apellido>Costas Huawei</apellido>
    <telefono>+34456123123</telefono>
    <Tarjeta_credito>1234567890123456</Tarjeta_credito>
    <Correo_electronico>alcalde@example.com</Correo_electronico>
</alcalde>
<funcionarios>
    <funcionario Id="abc123">
        <Nombre_completo>Felipoide</Nombre_completo>
        <Codigo_postal>28031</Codigo_postal>
        <fecha_nacimiento>01/02/1995</fecha_nacimiento>
        <contrasenia>A23@23232323</contrasenia>
        <Cuenta_bancaria>ES9876 5432 1098 7654</Cuenta_bancaria>

    </funcionario>
</funcionarios>
</Ciudad>
