<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE videojuego [
    <!ELEMENT videojuego (caracteristicas_videojuego, lista_programadores,compañia)>
    <!ELEMENT caracteristicas_videojuego (nombre,fecha_creación,nota)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT fecha_creación (#PCDATA)>
    <!ELEMENT nota (#PCDATA)>
    <!ELEMENT lista_programadores (Programador+)>
    <!ELEMENT Programador (DNI,nombre,apeliidos,fecha_nacimiento,direccion)>
    <!ELEMENT DNI (#PCDATA)>
    <!ELEMENT apeliidos (#PCDATA)>
    <!ELEMENT fecha_nacimiento (#PCDATA)>
    <!ELEMENT direccion (tipos_de_via,nombre_via,codigo_postal,pais)>
    <!ELEMENT tipos_de_via (#PCDATA)>
    <!ELEMENT nombre_via (#PCDATA)>
    <!ELEMENT codigo_postal (#PCDATA)>
    <!ELEMENT pais (#PCDATA)>
    <!ELEMENT compañia (Nombre, NIF,direccion)>
    <!ELEMENT Nombre (#PCDATA)>
    <!ELEMENT NIF (#PCDATA)>

    <!ATTLIST videojuego id ID #REQUIRED>
    <!ATTLIST Programador id ID #REQUIRED>
    <!ATTLIST compañia id ID #REQUIRED>


]>

<videojuego id="D98561271D">
    <caracteristicas_videojuego>
        <nombre>Monster Hunter World</nombre>
        <fecha_creación>26/1/2018</fecha_creación>
        <nota>9/10</nota>
    </caracteristicas_videojuego>
    <lista_programadores>
            <Programador id="D1">
                <DNI>12345678A</DNI>
                <nombre>Ted</nombre>
                <apeliidos>Bundy</apeliidos>
                <fecha_nacimiento>24/11/1946</fecha_nacimiento>
                <direccion >
                    <tipos_de_via>Avenida</tipos_de_via>
                    <nombre_via>Avenida falsa 123</nombre_via>
                    <codigo_postal>31021</codigo_postal>
                    <pais>USA</pais>                
                </direccion>
            </Programador>
            <Programador id="D2">
                <DNI>87654321Z</DNI>
                <nombre>Jeffrey</nombre>
                <apeliidos>Epstein</apeliidos>
                <fecha_nacimiento>20/1/1953</fecha_nacimiento>
                <direccion>
                    <tipos_de_via>Calle</tipos_de_via>
                    <nombre_via>Tartaria</nombre_via>
                    <codigo_postal>31221</codigo_postal>
                    <pais>Desconocido</pais>
                </direccion>
            </Programador>  
    </lista_programadores>
    <compañia id="D3">
            <Nombre>Capcom</Nombre>
            <NIF>34353535253US</NIF>
            <direccion>
                    <tipos_de_via>Bulevard</tipos_de_via>
                    <nombre_via>UwU</nombre_via>
                    <codigo_postal>10000</codigo_postal>
                    <pais>Japón</pais>
            </direccion>

    </compañia>
    </videojuego>